### ISSUE TITLE
Pin Mkdocs Multirepo Plugin Version

### ISSUE THREAD

**Issue by jdoiro3** [josh-wong/josh-wong.github.io#4]
@josh-wong, I'd pin the version of this plugin for now since it's still in active development. The previous version had a bug.

`pip install mkdocs-multirepo-plugin==0.4.3`

https://github.com/josh-wong/josh-wong.github.io/blob/eae05d013e1757191154b8e8dafc0e8e81425610/.github/workflows/ci.yml#L18

**Comment by josh-wong** [comment]
Thanks for helping me try to trouble shoot this issue! I can't seem to fix the problem, so I'm closing this issue until I can find time to look into the cause. 

**Reference:** [Issue #3 comment](https://github.com/josh-wong/josh-wong.github.io/issues/3#issuecomment-1183202354).
